[package]
name = "library"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
safe-regex = { version = "0.3.0", default-features = false }
arrayvec = { version = "0.7.6", default-features = false }
itertools = { version = "0.13.0", default-features = false }
micromath = "2.1.0"
array-init = { version = "2.1.0", default-features = false }
const_soft_float = { version = "0.1.4", features = ["no_std"] }
