[build]
target = "avr-specs/avr-atmega2560.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude mega2560 -cb 57600"
rustflags = [
  "-C", "inline-threshold=123", # +
]

[unstable]
build-std = ["core", "compiler_builtins", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
location-detail = ["none"]
fmt-debug = ["none"]
